# Generated by Django 4.0.2 on 2025-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('h2_count', models.PositiveIntegerField(default=0)),
                ('h3_count', models.PositiveIntegerField(default=0)),
                ('a_links', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
